steps:
  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ${FEDIVERSER_DOCKER_IMAGE:-mushroomlabs/fediverser}
      platforms: linux/amd64,linux/arm64
      registry: ${FEDIVERSER_DOCKER_REGISTRY:-https://index.docker.io/v1/}
      username:
        from_secret: docker_registry_user
      password:
        from_secret: docker_registry_pass
      tags:
        - ${CI_COMMIT_TAG:-latest}
        - ${CI_COMMIT_BRANCH}

when:
  branch:
    - master

  event:
    - manual
    - tag

depends_on:
  - test
